Update compatibility tests for clients
apecloud/myduckserver pull request #218
Opened 2024-11-26 11:28 UTC by NoyException

2024-11-26 12:09 UTC, TianyuZhang1214 commented
It seems all tests for MySQL failed?

2024-11-26 12:22 UTC, fanyang01 commented
Great work! So many programming languages :-)

I guess these failures could be resolved by a simple fix. Could you please look into it?

2024-11-27 09:54 UTC, TianyuZhang1214 requested changes

2024-11-27 09:54 UTC, TianyuZhang1214 commented on compatibility/mysql/c/mysql_test.c
> +size_t removeNewline(char *line) {
seems dumplicated: 
```c
size_t removeNewline(char *line) {
    size_t len = strlen(line);
    while (len > 0 && (line[len - 1] == '\n' || line[len - 1] == '\r')) {
        line[--len] = '\0';
    }
    return len;
}
```

2024-11-27 10:13 UTC, TianyuZhang1214 requested changes

2024-11-27 10:13 UTC, TianyuZhang1214 commented on compatibility/mysql/csharp/MySQLTest.cs
> +                string connectionString = $"Server={ip};Port={port};User Id={user};Password={password};";
This line should be moved in front of the try-catch block:
```cs
string connectionString = $"Server={ip};Port={port};User Id={user};Password={password};";
```

2024-11-27 10:13 UTC, TianyuZhang1214 commented on compatibility/mysql/csharp/MySQLTest.cs
> +                throw new Exception(e.Message);
Please add necessary prefix for all `Exception`. For example, the `Exception` here can be: 
```cs
                throw new Exception($"Failed to connect to MySQL server: {ex.Message}", ex);

```

2024-11-27 10:13 UTC, TianyuZhang1214 commented on compatibility/mysql/csharp/MySQLTest.cs
> +                        if (!reader.HasRows)
It's better to move result validation logic to a separate method `ValidateResults`.

2024-11-27 10:13 UTC, fanyang01 commented
Why does the Postgres compatiability test fail for more languages? Previously, it only failed for Java.

2024-11-27 10:41 UTC, TianyuZhang1214 requested changes

2024-11-27 10:41 UTC, TianyuZhang1214 commented on compatibility/mysql/go/mysql.go
> +				query = ""
```go
query, results = "", nil
```

2024-11-27 10:41 UTC, TianyuZhang1214 commented on compatibility/mysql/go/mysql.go
> +	tests.readTestsFromFile(testFile)
```go
    defer tests.disconnect()

	tests.readTestsFromFile(testFile)

	if !tests.runTests() {
		os.Exit(1)
	}
```

2024-11-27 10:41 UTC, TianyuZhang1214 commented on compatibility/mysql/go/mysql.go
> +				fmt.Printf("Expected: '%s', got: '%s'\n", expected, row[i])
Print the row id here: 
```go
fmt.Printf("Mismatch at row %d, column %d: expected '%s', got '%s'\n", rowCount+1, i+1, expected, row[i])
```

2024-11-27 10:58 UTC, fanyang01 commented
Let's comment out failed languages to make the CI health and fix the failures one-by-one in the next step.

2024-11-28 08:42 UTC, TianyuZhang1214 commented on compatibility/mysql/csharp/MySQLTest.cs
> +                        if (!reader.HasRows)
Got it, let's keep this one as it is.

2024-11-28 10:11 UTC, merged