feat: add support for managing multiple databases
apecloud/myduckserver pull request #307
Opened 2024-12-23 05:20 UTC by NoyException

2024-12-23 10:46 UTC, TianyuZhang1214 requested changes
Please add tests for this PR.

2024-12-23 17:19 UTC, fanyang01 commented on catalog/provider.go
> +func (prov *DatabaseProvider) CreateCatalog(dbFile string) (bool, error) {
Maybe we should simplify the `*Catalog` APIs to accept a catalog name without the `.db` suffix.

2024-12-24 08:51 UTC, TianyuZhang1214 requested changes
Great job!

2024-12-24 08:51 UTC, TianyuZhang1214 commented on catalog/internal_tables.go
> +	//if it.Schema == "__sys__" {
remove unnecessary comment here

2024-12-24 08:51 UTC, TianyuZhang1214 commented on catalog/provider.go
> +func NewDBProvider(defaultTimeZone, dataDir, defaultDB string) (prov *DatabaseProvider, err error) {
It seems we don't have strategy to scan all .db files under the data dir and attach them to current datbase?

2024-12-24 08:51 UTC, TianyuZhang1214 commented on catalog/provider.go
> +	pool                      *ConnectionPool // TODO(Noy): Merge into the provider
It's better to make it an issue of refactoring.

2024-12-25 06:37 UTC, TianyuZhang1214 approved these changes
LGTM

2024-12-25 06:41 UTC, merged